/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class FileRead */

#ifndef _Included_FileRead
#define _Included_FileRead
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     FileRead
 * Method:    addRow
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_FileRead_addRow
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring, jstring);

/*
 * Class:     FileRead
 * Method:    removeRow
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_FileRead_removeRow
  (JNIEnv *, jobject, jstring);

/*
 * Class:     FileRead
 * Method:    updateRow
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_FileRead_updateRow
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     FileRead
 * Method:    searchRow
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_FileRead_searchRow
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
